<?php
$this->title = "Clientes";
$this->headTitle($this->title);
?>

<section>
    <h4>Cadastro</h4>
    <div class="table-wrapper">

        <ul class="actions">
            <li><a href="/cadastro" class="button alt">Adicionar</a></li>
        </ul>

        <table>
            <tr>
                <th align="left">Id</th>
                <th align="left">Nome</th>
                <th align="left">Email</th>
                <th align="left">Telefone</th>
                <th align="left">CPF</th>
                <th align="left">&nbsp</th>
            </tr>

            <?php

            foreach ($this->entries as $line){
                $fields = explode(",",$line);
                echo "<tr>";
                foreach ($fields as $field){
                    echo "<td>" . str_replace('"','',$field) . "</td>";
                }
                echo '<td>' . '<a href="alteracao/id/'.$fields[0].'">Edit</a>' . '&nbsp<a href="exclusao/id/'.$fields[0].'">Delete</a>' . '</td>';
                echo "</tr>";
            }
            ?>

        </table>

    </div>
</section>
