<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Accenture</title>
    <?php echo $this->headLink()->appendStylesheet('/style.css') ?>
</head>
<body>
<!--
<div id="header">
    <div id="header-logo">
        <b>Sistema de Cadastro de Clientes</b>
    </div>
    <div id="header-navigation">
        <a href="/clientes">Clientes</a>
    </div>
</div>
-->

<header id="header">
    <div class="inner">
        <a href="/acc" class="logo">Accenture</a>
        <nav id="nav">
            <a href="/acc">Principal</a>
            <a href="/clientes">Cadastro</a>
        </nav>
    </div>
</header>
<section id="one">
    <div class="inner">
        <?php echo $this->layout()->content ?>
    </div>
</section>

</body>
</html>